name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)