name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: codecov/codecov-action@v1
    - name: Upload coverage to Codecov
      use: ./
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.out
        flags: unittest
        env_vars: OS,GO
        name: codecov-test
        fail_ci_if_error: true